name: Convert JSON to Parquet and Release

on:
  schedule:
    - cron: "0 6 * * *"   # medianoche CDMX (UTC-6 = 06:00 UTC)
  workflow_dispatch:

jobs:
  convert-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pandas pyarrow fastparquet

      - name: Convert JSON to Parquet
        run: |
          mkdir -p Finance_Analysis/datos_json
          python - <<EOF
          import pandas as pd

          files = {
              "Finance_Analysis/contribucion/test/dataBases/indicadores_de_trading/bolsa_estados_unidos/bolsa_estados_unidos_ind_trading.json": 
              "Finance_Analysis/datos_json/bolsa_estados_unidos_ind_trading.parquet",
              "Finance_Analysis/contribucion/test/dataBases/indicadores_de_trading/bolsa_mexicana_de_valores/bolsa_mexicana_de_valores_ind_trading.json": 
              "Finance_Analysis/datos_json/bolsa_mexicana_de_valores_ind_trading.parquet"
          }

          for src, dst in files.items():
              df = pd.read_json(src, lines=False)
              df.to_parquet(dst, engine="pyarrow", index=False)
              print(f"Convertido {src} -> {dst}")
          EOF

      - name: Create or Update Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: daily-parquet
          name: Daily Parquet Release
          draft: false
          prerelease: false
          files: |
            Finance_Analysis/datos_json/*.parquet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
