name: Convert JSON to Parquet and Upload to OneDrive

on:
  schedule:
    - cron: "0 6 * * *"   # medianoche CDMX (UTC-6 = 06:00 UTC)
  workflow_dispatch:

jobs:
  convert-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pandas pyarrow fastparquet

      - name: Convert JSON to Parquet
        run: |
          mkdir -p datos_json
          python - <<EOF
          import pandas as pd

          files = {
              "contribucion/test/dataBases/indicadores_de_trading/bolsa_estados_unidos/bolsa_estados_unidos_ind_trading.json": 
              "datos_json/bolsa_estados_unidos_ind_trading.parquet",
              "contribucion/test/dataBases/indicadores_de_trading/bolsa_mexicana_de_valores/bolsa_mexicana_de_valores_ind_trading.json": 
              "datos_json/bolsa_mexicana_de_valores_ind_trading.parquet"
          }

          for src, dst in files.items():
              df = pd.read_json(src, lines=False)
              df.to_parquet(dst, engine="pyarrow", index=False)
              print(f"Convertido {src} -> {dst}")
          EOF

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: Upload to OneDrive
        run: |
          rclone copy datos_json/ "onedrive:EmVM6J5YfU5OlWFdgnPKquoBA_Rn7-T1GkEcd5OhohyxaQ" --progress
