name: Descargar datos BMV

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub
  schedule:
    - cron: '30 21 * * 1-5' # Corre lunes a viernes a las 16:30 hora del centro de México (21:30 UTC)

jobs:
  descargar:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install yfinance pandas

    - name: Ejecutar script
      run: python descargar_datos_bmv.py

    - name: Subir archivos CSV generados
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add datos_bmv/*.csv
        git commit -m "Agregar archivos CSV con datos BMV actualizados"
        git push
