name: Descargar datos US

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  descargar:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install yfinance pandas

    - name: Ejecutar script
      run: python Descarga_datos_us.py

    - name: Subir archivos CSV generados
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add datos_us/*.csv
        git commit -m "Agregar archivos CSV con datos US actualizados"
        git push
