# This workflow will run per_calculator.py script and create FinanzPER.json over main/json folder

name: Generar FinanzPER

on:
  workflow_dispatch: # se puede ejecutar manualmente
  schedule:
    - cron: "0 23 * * 1-5" # corre de lunes a viernes a las 12:00 UTC (17:00 hrs. Mexico)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install yfinance pandas

      - name: Ejecutar script
        run: python per_calculator.py

      - name: Commit y Push FinanzPER.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add datos_json/FinanzPER.json
          git commit -m "Actualizar FinanzPER.json"
          git push
